app:
  security:
    enabled: true
  proxy:
    host: ${HTTPS_PROXY_HOST:proxy.example.com}
    port: ${HTTPS_PROXY_PORT:3128}
  config:
    oidcuuid: uuid
spring:
  main:
    lazy-initialization: true
  neo4j:
    uri: ${NEO4J_URI:bolt+s://demo.neo4jlabs.com:7687}
    database: ${NEO4J_DB:movies}
    authentication:
      username: ${NEO4J_USERNAME:movies}
      password: ${NEO4J_PASSWORD:movies}
    driver:
      encrypted: true
      trust-strategy:
        strategy: TRUST_ALL_CERTIFICATES
  data:
    rest:
      base-path: /api
      default-page-size: 50
  security:
    enabled: true
    filter-chain.enabled: true # disables the default chain.
    user:
      name: client
      password: client
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_URI}
          jwt-custom-uri: ${JWT_URI}
          connect-timeout: 5000
          read-timeout: 5000
      client:
        registration:
          keycloak:
            client-id: ${OIDC_CLIENTID}
            client-secret: ${OIDC_CLIENTSECRET}
            authorization-grant-type: authorization_code
            scope: ${OIDC_SCOPE:openid}
            provider: keycloak
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          keycloak:
            issuer-uri: ${OIDC_ISSUERURI}
            authorization-uri: ${OIDC_AUTHURI}
            token-uri: ${OIDC_TOKENURI}
            user-info-uri: ${OIDC_USERURI}
            jwk-set-uri: ${OIDC_JWKCRTURI}

springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: false
  auto-tag-classes: false
  model-and-view-allowed: false

server:
  address: 0.0.0.0
  port: ${SPRINGBOOT_PORT:8080}
  connection-timeout: 5s
  forward-headers-strategy: framework # baseUrl based on X-Forwarded-Host/X-Forwarded-Proto
management:
  server:
    port: ${SPRINGBOOT_HEALTHPORT:8091}
  endpoints:
    web:
      exposure:
        include: health # Only expose the health endpoint

logging:
  level:
    org.neo4j.driver: ${SPRINGBOOT_LOGLEVEL:WARN}
    javax.net.ssl: ${SPRINGBOOT_LOGLEVEL:WARN}
    org.springframework.data.neo4j.core: ${SPRINGBOOT_LOGLEVEL:WARN}
    #org.springframework.security.saml2: ERROR
    #org.springframework.security: ERROR
